"use client";

import { useActionState } from "react";
import { createCouponAction, createShippingMethodAction, createShippingZoneAction, setCouponActiveAction, updateReturnAction } from "../commerce-actions";
import { initialActionState } from "../action-state";
import { ActionMessage } from "./ActionMessage";
import { ConfirmActionButton } from "./ConfirmActionButton";
import { SubmitButton } from "./SubmitButton";

type Props = { zones: any[]; methods: any[]; coupons: any[]; returns: any[]; refunds: any[] };

export function CommerceManager({ zones, methods, coupons, returns, refunds }: Props) {
  const [zoneState, zoneAction] = useActionState(createShippingZoneAction, initialActionState);
  const [methodState, methodAction] = useActionState(createShippingMethodAction, initialActionState);
  const [couponState, couponAction] = useActionState(createCouponAction, initialActionState);
  return <div className="space-y-8">
    <section className="grid gap-6 xl:grid-cols-2">
      <form action={zoneAction} className="staff-panel space-y-4 p-5"><h2 className="text-lg font-bold">Add shipping zone</h2><ActionMessage state={zoneState} /><label><span className="staff-label">Name</span><input name="name" required className="staff-input" /></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="staff-label">Market</span><select name="country_code" className="staff-input"><option value="LK">Sri Lanka</option><option value="AE">UAE</option></select></label><label><span className="staff-label">District / emirate group</span><input name="region_name" className="staff-input" /></label></div><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="active" value="true" />Active</label><SubmitButton>Add zone</SubmitButton></form>
      <form action={methodAction} className="staff-panel space-y-4 p-5"><h2 className="text-lg font-bold">Add shipping method / fallback rate</h2><ActionMessage state={methodState} /><label><span className="staff-label">Zone</span><select name="shipping_zone_id" required className="staff-input"><option value="">Choose zone</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name} · {zone.country_code}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="staff-label">Method name</span><input name="name" required className="staff-input" /></label><label><span className="staff-label">Currency</span><select name="currency" className="staff-input"><option>LKR</option><option>AED</option></select></label><label><span className="staff-label">Fallback fee</span><input name="fee" type="number" min="0" step="0.01" required className="staff-input" /></label><label><span className="staff-label">Free threshold</span><input name="free_shipping_threshold" type="number" min="0" step="0.01" className="staff-input" /></label><label><span className="staff-label">Minimum days</span><input name="estimated_min_days" type="number" min="0" defaultValue="1" required className="staff-input" /></label><label><span className="staff-label">Maximum days</span><input name="estimated_max_days" type="number" min="0" defaultValue="3" required className="staff-input" /></label></div><label><span className="staff-label">Description</span><textarea name="description" className="staff-input" /></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="active" value="true" />Active</label><SubmitButton>Add method</SubmitButton></form>
    </section>
    <section className="staff-panel p-5"><h2 className="text-lg font-bold">Configured delivery</h2>{methods.length ? <div className="staff-table-wrap mt-4"><table className="staff-table"><thead><tr><th>Zone</th><th>Method</th><th>Rate</th><th>Estimate</th><th>State</th></tr></thead><tbody>{methods.map((method) => <tr key={method.id}><td>{method.shipping_zones?.name}</td><td>{method.name}</td><td>{method.currency} {Number(method.fee).toFixed(2)}</td><td>{method.estimated_min_days}–{method.estimated_max_days} days</td><td>{method.active ? "Active" : "Inactive"}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-amber-800">No delivery method is configured. Product-level fees may still calculate, but no selectable method or estimate is available.</p>}</section>
    <section className="grid gap-6 xl:grid-cols-[420px_1fr]">
      <form action={couponAction} className="staff-panel space-y-4 p-5"><h2 className="text-lg font-bold">Create coupon</h2><ActionMessage state={couponState} /><div className="grid gap-4 sm:grid-cols-2"><label><span className="staff-label">Code</span><input name="code" required className="staff-input uppercase" /></label><label><span className="staff-label">Market</span><select name="country_scope" className="staff-input"><option value="both">Both</option><option value="sri-lanka">Sri Lanka</option><option value="uae">UAE</option></select></label><label><span className="staff-label">Type</span><select name="discount_type" className="staff-input"><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select></label><label><span className="staff-label">Value</span><input name="discount_value" type="number" min="0.01" step="0.01" required className="staff-input" /></label><label><span className="staff-label">Minimum order</span><input name="minimum_order_amount" type="number" min="0" step="0.01" defaultValue="0" className="staff-input" /></label><label><span className="staff-label">Maximum discount</span><input name="maximum_discount" type="number" min="0" step="0.01" className="staff-input" /></label><label><span className="staff-label">Usage limit</span><input name="usage_limit" type="number" min="1" className="staff-input" /></label><label><span className="staff-label">Per customer</span><input name="per_customer_limit" type="number" min="1" defaultValue="1" className="staff-input" /></label><label><span className="staff-label">Starts</span><input name="starts_at" type="datetime-local" className="staff-input" /></label><label><span className="staff-label">Expires</span><input name="ends_at" type="datetime-local" className="staff-input" /></label></div><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="active" value="true" />Active immediately</label><SubmitButton>Create coupon</SubmitButton></form>
      <section className="staff-panel p-5"><h2 className="text-lg font-bold">Coupons</h2>{coupons.length ? <div className="staff-table-wrap mt-4"><table className="staff-table"><thead><tr><th>Code</th><th>Discount</th><th>Market</th><th>Usage</th><th>State</th><th>Action</th></tr></thead><tbody>{coupons.map((coupon) => <tr key={coupon.id}><td className="font-mono font-bold">{coupon.code}</td><td>{coupon.discount_type === "percentage" ? `${coupon.discount_value}%` : Number(coupon.discount_value).toFixed(2)}</td><td>{coupon.country_scope}</td><td>{coupon.coupon_redemptions?.[0]?.count ?? 0}{coupon.usage_limit ? ` / ${coupon.usage_limit}` : ""}</td><td>{coupon.active ? "Active" : "Inactive"}</td><td><ConfirmActionButton action={setCouponActiveAction.bind(null, coupon.id, !coupon.active)} label={coupon.active ? "Disable" : "Enable"} title={`${coupon.active ? "Disable" : "Enable"} ${coupon.code}?`} detail="The change applies to new checkout validations immediately." /></td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-slate-500">No coupons created.</p>}</section>
    </section>
    <section className="staff-panel p-5"><h2 className="text-lg font-bold">Return requests</h2>{returns.length ? <div className="mt-4 grid gap-4">{returns.map((request) => <ReturnCard key={request.id} request={request} />)}</div> : <p className="mt-4 text-sm text-slate-500">No return requests.</p>}</section>
    <section className="staff-panel p-5"><h2 className="text-lg font-bold">Refund history</h2>{refunds.length ? <div className="staff-table-wrap mt-4"><table className="staff-table"><thead><tr><th>Order</th><th>Amount</th><th>Type</th><th>Status</th><th>Reason</th></tr></thead><tbody>{refunds.map((refund) => <tr key={refund.id}><td>{refund.orders?.order_number}</td><td>{refund.currency} {Number(refund.amount).toFixed(2)}</td><td>{refund.refund_type}</td><td>{refund.status}</td><td>{refund.reason}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-slate-500">No refund records.</p>}</section>
  </div>;
}

function ReturnCard({ request }: { request: any }) {
  const [state, action] = useActionState(updateReturnAction.bind(null, request.id), initialActionState);
  return <article className="rounded-xl border border-[var(--staff-line)] p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-xs font-bold">{request.orders?.order_number}</p><p className="mt-1 font-semibold">{request.reason}</p><p className="mt-1 text-sm text-slate-500">{request.customer_note || "No customer note."}</p></div><span className="capitalize">{request.status.replaceAll("_", " ")}</span></div><form action={action} className="mt-4 grid gap-3 md:grid-cols-[190px_1fr_auto]"><ActionMessage state={state} /><select name="status" defaultValue={request.status} className="staff-input">{["requested","more_information","approved","rejected","received","inspected","restocked","resolved","cancelled"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><input name="admin_note" className="staff-input" placeholder="Internal/customer handling note" maxLength={2000} /><SubmitButton>Update</SubmitButton></form></article>;
}
