"use client";

import { Search, SlidersHorizontal as MinusPlus } from "lucide-react";
import { useActionState, useMemo, useRef, useState } from "react";
import type { Product, StockMovement } from "@/lib/supabase/types";
import { initialActionState } from "../action-state";
import { adjustStockAction } from "../actions";
import { formatDate } from "../lib/format";
import { ActionMessage } from "./ActionMessage";
import { EmptyState } from "./EmptyState";
import { SubmitButton } from "./SubmitButton";

function AdjustmentDialog({ product }: { product: Product }) {
  const dialogRef = useRef<HTMLDialogElement>(null); const [state, action] = useActionState(adjustStockAction, initialActionState);
  return <><button className="staff-button staff-button-secondary" onClick={() => dialogRef.current?.showModal()}><MinusPlus className="h-4 w-4" />Adjust</button><dialog ref={dialogRef} className="staff-dialog"><form action={action} className="space-y-4 p-6 sm:p-8"><input type="hidden" name="product_id" value={product.id} /><h2 className="text-xl font-bold">Adjust {product.name}</h2><p className="text-sm text-slate-500">Current stock: <strong>{product.stock_quantity}</strong>. Use a negative number to remove stock.</p><ActionMessage state={state} /><label><span className="staff-label">Quantity change *</span><input className="staff-input" name="quantity_change" type="number" step="1" required placeholder="e.g. 10 or -2" /></label><label><span className="staff-label">Movement type</span><select className="staff-input" name="movement_type"><option value="restock">Restock</option><option value="manual_adjustment">Manual adjustment</option></select></label><div className="flex justify-end gap-3"><button type="button" className="staff-button staff-button-secondary" onClick={() => dialogRef.current?.close()}>Close</button><SubmitButton>Update stock</SubmitButton></div></form></dialog></>;
}

export function InventoryManager({ products, movements }: { products: Product[]; movements: StockMovement[] }) {
  const [query, setQuery] = useState(""); const [lowOnly, setLowOnly] = useState(false);
  const rows = useMemo(() => products.filter((p) => (!lowOnly || p.stock_quantity <= p.low_stock_alert) && `${p.name} ${p.sku} ${p.barcode ?? ""}`.toLowerCase().includes(query.toLowerCase())), [products, query, lowOnly]);
  return <div className="space-y-6"><section className="staff-panel"><div className="flex flex-col gap-3 border-b border-[var(--staff-line)] p-4 sm:flex-row sm:items-center"><label className="relative flex-1"><span className="sr-only">Search stock</span><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input className="staff-input pl-10" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search product, SKU, or barcode" /></label><label className="flex min-h-11 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={lowOnly} onChange={(e) => setLowOnly(e.target.checked)} className="h-4 w-4 accent-yara-wine" />Low stock only</label></div>{rows.length ? <div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Product</th><th>SKU</th><th>Current stock</th><th>Alert at</th><th>Health</th><th>Action</th></tr></thead><tbody>{rows.map((product) => { const low = product.stock_quantity <= product.low_stock_alert; return <tr key={product.id}><td className="font-semibold">{product.name}</td><td className="font-mono text-xs">{product.sku}</td><td className="staff-metric text-lg font-bold">{product.stock_quantity}</td><td className="staff-metric">{product.low_stock_alert}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${low ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-700"}`}>{low ? "Low stock" : "Healthy"}</span></td><td><AdjustmentDialog product={product} /></td></tr>; })}</tbody></table></div> : <EmptyState title="No stock records found" detail="Adjust the search or low-stock filter." />}</section><section className="staff-panel"><div className="border-b border-[var(--staff-line)] p-5"><h2 className="font-bold">Stock movement history</h2><p className="mt-1 text-xs text-slate-500">Most recent 100 movements</p></div>{movements.length ? <div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Change</th><th>Stock</th><th>Staff</th></tr></thead><tbody>{movements.map((movement) => <tr key={movement.id}><td className="text-xs text-slate-500">{formatDate(movement.created_at, true)}</td><td><p className="font-semibold">{movement.products?.name ?? "Unknown"}</p><p className="font-mono text-xs text-slate-400">{movement.products?.sku}</p></td><td className="capitalize">{movement.movement_type.replaceAll("_", " ")}</td><td className={`staff-metric font-bold ${movement.quantity_change > 0 ? "text-emerald-700" : "text-red-700"}`}>{movement.quantity_change > 0 ? "+" : ""}{movement.quantity_change}</td><td className="staff-metric">{movement.previous_stock} → {movement.new_stock}</td><td>{movement.profiles?.full_name ?? "System"}</td></tr>)}</tbody></table></div> : <EmptyState title="No stock movements" detail="Adjustments and sales will appear here." />}</section></div>;
}
