import { getCustomers } from "./data";
import { formatDate, formatMoney } from "./lib/format";
import { EmptyState } from "./components/EmptyState";
import { PageHeader } from "./components/PageHeader";

export async function AdminCustomersPage() {
  const { profiles, orders } = await getCustomers();
  const keys = new Set([...profiles.map((p) => p.email.toLowerCase()), ...orders.map((o) => o.customer_email.toLowerCase())]);
  const customers = [...keys].map((email) => { const profile = profiles.find((p) => p.email.toLowerCase() === email); const history = orders.filter((o) => o.customer_email.toLowerCase() === email); return { id: profile?.id ?? email, name: profile?.full_name || history[0]?.customer_name || "Guest customer", email, phone: history.find((o) => o.customer_phone)?.customer_phone || "—", joined: profile?.created_at ?? history.at(-1)?.created_at ?? new Date().toISOString(), history, total: history.filter((o) => o.order_status !== "cancelled").reduce((sum, o) => sum + Number(o.total_amount), 0) }; });
  return <><PageHeader eyebrow="Relationships" title="Customers" description="Contact details and online order history for registered and guest customers." /><section className="staff-panel">{customers.length ? <div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Customer</th><th>Contact</th><th>Orders</th><th>Lifetime value</th><th>Latest order</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><p className="font-semibold">{customer.name}</p><p className="text-xs text-slate-500">Since {formatDate(customer.joined)}</p></td><td><p>{customer.email}</p><p className="text-xs text-slate-500">{customer.phone}</p></td><td><details><summary className="cursor-pointer font-semibold text-yara-wine">{customer.history.length} order{customer.history.length === 1 ? "" : "s"}</summary><ul className="mt-2 space-y-1 text-xs">{customer.history.slice(0, 5).map((order) => <li key={order.id}>{order.order_number} · {formatMoney(Number(order.total_amount), order.currency)}</li>)}</ul></details></td><td className="staff-metric font-semibold">{formatMoney(customer.total)}</td><td>{customer.history[0] ? formatDate(customer.history[0].created_at) : "—"}</td></tr>)}</tbody></table></div> : <EmptyState title="No customers yet" detail="Customer profiles and order contacts will appear here." />}</section></>;
}
