import { getCoupons } from "./data";
import { saveCouponAction } from "./actions";
import { PageHeader } from "./components/PageHeader";

export async function AdminCouponsPage() {
  const coupons = await getCoupons();
  return <>
    <PageHeader eyebrow="Marketing" title="Coupons" description="Create server-validated fixed or percentage discounts with regional and usage limits." />
    <section className="staff-panel p-5 sm:p-6"><h2 className="font-bold">Create coupon</h2><form action={saveCouponAction} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="block"><span className="field-label">Code</span><input name="code" required maxLength={64} className="field" placeholder="WELCOME10" /></label><label className="block"><span className="field-label">Type</span><select name="discount_type" className="field" defaultValue="percentage"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label><label className="block"><span className="field-label">Value</span><input name="discount_value" type="number" min="0.01" step="0.01" required className="field" /></label><label className="block"><span className="field-label">Region</span><select name="country_scope" className="field" defaultValue="both"><option value="both">Sri Lanka and UAE</option><option value="sri-lanka">Sri Lanka only</option><option value="uae">UAE only</option></select></label><label className="block"><span className="field-label">Minimum order</span><input name="minimum_order_amount" type="number" min="0" step="0.01" defaultValue="0" className="field" /></label><label className="block"><span className="field-label">Maximum discount (optional)</span><input name="maximum_discount" type="number" min="0" step="0.01" className="field" /></label><label className="block"><span className="field-label">Usage limit (optional)</span><input name="usage_limit" type="number" min="1" step="1" className="field" /></label><label className="block"><span className="field-label">Per customer/email</span><input name="per_customer_limit" type="number" min="1" step="1" defaultValue="1" className="field" /></label><label className="block"><span className="field-label">Starts at (optional)</span><input name="starts_at" type="datetime-local" className="field" /></label><label className="block"><span className="field-label">Ends at (optional)</span><input name="ends_at" type="datetime-local" className="field" /></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="active" /> Activate coupon</label><button className="staff-button staff-button-primary" type="submit">Save coupon</button></form></section>
    <section className="staff-panel mt-6 p-5 sm:p-6"><h2 className="font-bold">Coupons</h2><div className="staff-table-wrap mt-5"><table className="staff-table"><thead><tr><th>Code</th><th>Type</th><th>Region</th><th>Value</th><th>Status</th></tr></thead><tbody>{coupons.map((coupon) => <tr key={coupon.id}><td className="font-mono font-semibold">{coupon.code}</td><td>{coupon.discount_type}</td><td>{coupon.country_scope}</td><td className="staff-metric">{coupon.discount_value}</td><td>{coupon.active ? "Active" : "Inactive"}</td></tr>)}{!coupons.length && <tr><td colSpan={5}>No coupons configured.</td></tr>}</tbody></table></div></section>
  </>;
}
