import { getShippingConfiguration } from "./data";
import { saveShippingMethodAction, saveShippingZoneAction } from "./actions";
import { PageHeader } from "./components/PageHeader";

export async function AdminShippingPage() {
  const { zones, methods } = await getShippingConfiguration();
  return <>
    <PageHeader eyebrow="Fulfilment" title="Shipping configuration" description="Configure separate Sri Lanka and UAE delivery rules. New methods are inactive until you approve their fees." />
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <section className="staff-panel p-5 sm:p-6"><h2 className="font-bold">Add shipping zone</h2><form action={saveShippingZoneAction} className="mt-5 space-y-4"><label className="block"><span className="field-label">Name</span><input name="name" required className="field" placeholder="Sri Lanka nationwide" /></label><label className="block"><span className="field-label">Country</span><select name="country_code" className="field" defaultValue="LK"><option value="LK">Sri Lanka</option><option value="AE">UAE</option></select></label><label className="block"><span className="field-label">Region (optional)</span><input name="region_name" className="field" placeholder="Nationwide or emirate" /></label><label className="block"><span className="field-label">Sort order</span><input name="sort_order" type="number" defaultValue="0" className="field" /></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="active" /> Active</label><button className="staff-button staff-button-primary" type="submit">Save zone</button></form></section>
      <section className="staff-panel p-5 sm:p-6"><h2 className="font-bold">Add shipping method</h2>{!zones.length && <p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Create a zone first. Do not activate a method until the business has approved its fee and delivery estimate.</p>}<form action={saveShippingMethodAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="block"><span className="field-label">Zone</span><select name="shipping_zone_id" required className="field" defaultValue=""><option value="" disabled>Select zone</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name} ({zone.country_code})</option>)}</select></label><label className="block"><span className="field-label">Method name</span><input name="name" required className="field" placeholder="Standard delivery" /></label><label className="block sm:col-span-2"><span className="field-label">Description</span><input name="description" className="field" placeholder="Delivery estimate shown to customers" /></label><label className="block"><span className="field-label">Fee</span><input name="fee" type="number" min="0" step="0.01" required className="field" /></label><label className="block"><span className="field-label">Currency</span><select name="currency" className="field" defaultValue="LKR"><option value="LKR">LKR</option><option value="AED">AED</option></select></label><label className="block"><span className="field-label">Free above (optional)</span><input name="free_shipping_threshold" type="number" min="0" step="0.01" className="field" /></label><label className="block"><span className="field-label">Sort order</span><input name="sort_order" type="number" defaultValue="0" className="field" /></label><label className="block"><span className="field-label">Min days</span><input name="estimated_min_days" type="number" min="0" defaultValue="1" className="field" /></label><label className="block"><span className="field-label">Max days</span><input name="estimated_max_days" type="number" min="0" defaultValue="3" className="field" /></label><label className="flex items-center gap-3 text-sm sm:col-span-2"><input type="checkbox" name="active" /> Activate after verifying fee, currency, and estimate</label><button disabled={!zones.length} className="staff-button staff-button-primary sm:col-span-2 disabled:opacity-50" type="submit">Save shipping method</button></form></section>
    </div>
    <section className="staff-panel mt-6 p-5 sm:p-6"><h2 className="font-bold">Configured zones and methods</h2><div className="staff-table-wrap mt-5"><table className="staff-table"><thead><tr><th>Method</th><th>Zone</th><th>Fee</th><th>Estimate</th><th>Status</th></tr></thead><tbody>{methods.map((method) => <tr key={method.id}><td className="font-semibold">{method.name}</td><td>{method.shipping_zones?.name ?? "—"}</td><td className="staff-metric">{method.currency} {Number(method.fee).toFixed(2)}</td><td>{method.estimated_min_days}–{method.estimated_max_days} days</td><td>{method.active ? "Active" : "Inactive"}</td></tr>)}{!methods.length && <tr><td colSpan={5}>No shipping methods configured.</td></tr>}</tbody></table></div></section>
  </>;
}
